// Code generated by GinX. DO NOT EDIT.
package handler

import (
	"net/http"

	generated "MultiMediaManager/internal/generated"
	"MultiMediaManager/internal/logic"

	"github.com/gin-gonic/gin"
)

// Browse 浏览本地目录
func (h *Handler) Browse(c *gin.Context, params generated.BrowseParams) {
	l := logic.NewBrowseLogic(h.Logic)

	resp, err := l.Browse(params)

	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, resp)
}
