// Code generated by GinX. DO NOT EDIT.
package handler

import (
	"net/http"

	generated "Rivus/internal/generated"
	"Rivus/internal/logic"

	"github.com/gin-gonic/gin"
)

// FetchLyric 拉取歌词
func (h *Handler) FetchLyric(c *gin.Context, params generated.FetchLyricParams) {
	l := logic.NewFetchLyricLogic(h.Logic)

	resp, err := l.FetchLyric(params)

	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, resp)
}
