// Code generated by GinX. DO NOT EDIT.
package handler

import (
	"net/http"

	"Rivus/internal/logic"

	"github.com/gin-gonic/gin"
)

// GetConfig 获取配置接口
func (h *Handler) GetConfig(c *gin.Context) {
	l := logic.NewGetConfigLogic(h.Logic)

	resp, err := l.GetConfig()

	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, resp)
}
