// Code generated by GinX. DO NOT EDIT.
package handler

import (
	"net/http"

	generated "MultiMediaManager/internal/generated"
	"MultiMediaManager/internal/logic"

	"github.com/gin-gonic/gin"
)

// GetRecycleBin 获取回收站音频
func (h *Handler) GetRecycleBin(c *gin.Context, params generated.GetRecycleBinParams) {
	l := logic.NewGetRecycleBinLogic(h.Logic)

	resp, err := l.GetRecycleBin(params)

	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, resp)
}
