// Code generated by GinX. DO NOT EDIT.
package handler

import (
	"net/http"

	"MultiMediaManager/internal/logic"

	"github.com/gin-gonic/gin"
)

// Ping 健康检查接口
func (h *Handler) Ping(c *gin.Context) {
	l := logic.NewPingLogic(h.Logic)

	resp, err := l.Ping()

	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, resp)
}
