// Code generated by GinX. DO NOT EDIT.
package handler

import (
	"net/http"

	"Rivus/internal/logic"

	"github.com/gin-gonic/gin"
)

// ScanAudio 扫描音频目录，构建音频元数据
func (h *Handler) ScanAudio(c *gin.Context) {
	l := logic.NewScanAudioLogic(h.Logic)

	resp, err := l.ScanAudio()

	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, resp)
}
