// Code generated by GinX. DO NOT EDIT.
package handler

import (
	"net/http"

	generated "Rivus/internal/generated"
	"Rivus/internal/logic"

	"github.com/gin-gonic/gin"
)

// ScrapeAudio 刮削音频元数据
func (h *Handler) ScrapeAudio(c *gin.Context, params generated.ScrapeAudioParams) {
	l := logic.NewScrapeAudioLogic(h.Logic)

	resp, err := l.ScrapeAudio(params)

	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, resp)
}
