// Code generated by GinX. DO NOT EDIT.
package handler

import (
	"net/http"

	generated "Rivus/internal/generated"
	"Rivus/internal/logic"

	"github.com/gin-gonic/gin"
)

// SearchAudio 搜索音频
func (h *Handler) SearchAudio(c *gin.Context, params generated.SearchAudioParams) {
	l := logic.NewSearchAudioLogic(h.Logic)

	resp, err := l.SearchAudio(params)

	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, resp)
}
