// Code generated by GinX. DO NOT EDIT.
package handler

import (
	"net/http"

	"Rivus/internal/logic"

	"github.com/gin-gonic/gin"
)

// Shutdown 关闭服务
func (h *Handler) Shutdown(c *gin.Context) {
	l := logic.NewShutdownLogic(h.Logic)

	resp, err := l.Shutdown()

	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, resp)
}
