// Code generated by GinX. DO NOT EDIT.
package handler

import (
	"net/http"

	generated "Rivus/internal/generated"
	"Rivus/internal/logic"

	"github.com/gin-gonic/gin"
)

// SyncBrowse
func (h *Handler) SyncBrowse(c *gin.Context, params generated.SyncBrowseParams) {
	l := logic.NewSyncBrowseLogic(h.Logic)

	resp, err := l.SyncBrowse(params)

	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, resp)
}
