package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/getkin/kin-openapi/openapi3"
)

type HandlerInfo struct {
	OperationID  string
	Method       string
	Path         string
	Summary      string
	RequestType  string
	ResponseType string
	HasBody      bool
	HasParams    bool
}

func main() {
	// 参数：handler / logic / all
	genType := flag.String("type", "all", "生成类型: handler, logic, all")
	flag.Parse()

	loader := openapi3.NewLoader()
	doc, err := loader.LoadFromFile("docs/openapi.yaml")
	if err != nil {
		panic(err)
	}

	var handlers []HandlerInfo
	for path, item := range doc.Paths.Map() {
		for method, op := range item.Operations() {
			info := HandlerInfo{
				OperationID: op.OperationID,
				Method:      strings.ToUpper(method),
				Path:        path,
				Summary:     op.Summary,
			}

			if op.RequestBody != nil {
				for _, mt := range op.RequestBody.Value.Content {
					if mt.Schema != nil && mt.Schema.Ref != "" {
						info.RequestType = strings.TrimPrefix(mt.Schema.Ref, "#/components/schemas/")
						info.HasBody = true
					}
				}
			}

			if len(op.Parameters) > 0 {
				info.HasParams = true
			}

			if op.Responses != nil {
				for _, resp := range op.Responses.Map() {
					for _, mt := range resp.Value.Content {
						if mt.Schema != nil && mt.Schema.Ref != "" {
							info.ResponseType = strings.TrimPrefix(mt.Schema.Ref, "#/components/schemas/")
						}
					}
				}
			}

			handlers = append(handlers, info)
		}
	}

	for _, h := range handlers {
		switch *genType {
		case "handler":
			genHandlerFile(h)
		case "logic":
			genLogicFile(h)
		case "all":
			genHandlerFile(h)
			genLogicFile(h)
		default:
			fmt.Printf("❌ 未知类型: %s，请使用 handler/logic/all\n", *genType)
			return
		}
	}

	fmt.Printf("✅ %s 生成完成\n", *genType)
}

func genHandlerFile(info HandlerInfo) {
	tpl := `// Code generated by GinX. DO NOT EDIT.
package handler

import (
    "net/http"

    "github.com/gin-gonic/gin"
    generated "MultiMediaManager/internal/generated"
    "MultiMediaManager/internal/logic"
)

// {{.OperationID}} {{.Summary}}
func (h *Handler) {{.OperationID}}(c *gin.Context{{if .HasParams}}, params generated.{{.OperationID}}Params{{end}}) {
    l := logic.New{{.OperationID}}Logic(h.Logic)
    {{if .HasBody}}
    var req generated.{{.RequestType}}
    if err := c.ShouldBindJSON(&req); err != nil {
        c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
        return
    }
    resp, err := l.{{.OperationID}}(&req{{if .HasParams}}, params{{end}})
    {{else if .HasParams}}
    resp, err := l.{{.OperationID}}(params)
    {{else}}
    resp, err := l.{{.OperationID}}()
    {{end}}
    if err != nil {
        c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
        return
    }
    c.JSON(http.StatusOK, resp)
}
`

	tmpl := template.Must(template.New("handler").Parse(tpl))
	var buf bytes.Buffer
	tmpl.Execute(&buf, info)

	formatted, _ := format.Source(buf.Bytes())
	filename := fmt.Sprintf("internal/handler/%s.handler.go", toCamelCase(info.OperationID))
	os.MkdirAll(filepath.Dir(filename), 0755)
	os.WriteFile(filename, formatted, 0644)
	fmt.Printf("  ✅ %s\n", filename)
}

func genLogicFile(info HandlerInfo) {
	filename := fmt.Sprintf("internal/logic/%s.logic.go", toCamelCase(info.OperationID))
	if _, err := os.Stat(filename); err == nil {
		fmt.Printf("  ⏭️  %s (已存在，跳过)\n", filename)
		return
	}

	tpl := `package logic

import (
    generated "MultiMediaManager/internal/generated"
)

// {{.OperationID}}Logic {{.Summary}}
type {{.OperationID}}Logic struct {
    *Logic
}

func New{{.OperationID}}Logic(l *Logic) *{{.OperationID}}Logic {
    return &{{.OperationID}}Logic{Logic: l}
}

// {{.OperationID}} {{.Summary}}
func (l *{{.OperationID}}Logic) {{.OperationID}}({{if .HasBody}}req *generated.{{.RequestType}}{{end}}{{if and .HasBody .HasParams}}, {{end}}{{if .HasParams}}params generated.{{.OperationID}}Params{{end}}) (*generated.{{.ResponseType}}, error) {
    // TODO: 实现业务逻辑
    {{if .HasBody}}
    _ = req
    {{end}}
    {{if .HasParams}}
    _ = params
    {{end}}
    return &generated.{{.ResponseType}}{}, nil
}
`

	tmpl := template.Must(template.New("logic").Parse(tpl))
	var buf bytes.Buffer
	tmpl.Execute(&buf, info)

	formatted, _ := format.Source(buf.Bytes())
	os.MkdirAll(filepath.Dir(filename), 0755)
	os.WriteFile(filename, formatted, 0644)
	fmt.Printf("  ✅ %s\n", filename)
}

func toCamelCase(s string) string {
	if s == "" {
		return ""
	}
	return strings.ToLower(s[:1]) + s[1:]
}
